- name: Deploy Backend
  hosts: backend
  become: yes
  vars_files:
    - /vagrant_data/teachua/ansible/group_vars/backend.yml
  roles:
    - backend

#- name: Set up SSH keys
#  hosts: all
#  become: yes
#  tasks:
#    - name: Create .ssh directory
#      file:
#        path: "~/.ssh"
#        state: directory
#        mode: '0700'

#    - name: Add public key to authorized_keys
#      authorized_key:
#        user: "{{ ansible_user }}"
#        state: present
#        key: "{{ lookup('file', '/home/codespace/.ssh/id_rsa.pub') }}"





















    
  tasks:
    - name: Allow port 8080 for backend application
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 8080
        jump: ACCEPT
    - name: Allow port 3306 for MariaDB
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 3306
        jump: ACCEPT
    - name: Save iptables rules
      command: iptables-save  
