# Services and their SSH ports:
# database: 8000
# backend_deploy: 8001
# frontend_deploy: 8002
# build_backend: 8003
# build_frontend: 8004
# load_balancer: 8005
# file_system: 8006
# artifacts: 8007
# jenkins: 8008

#[containers]
#backend_deploy = 172.18.0.2
#jenkins = 172.18.0.3
#frontend_deploy = 172.18.0.7
#build_frontend = 172.18.0.6
#build_backend = 172.18.0.5
#database = 172.18.0.4

all:
  hosts:
    database:
      ansible_host: 172.18.0.5
      ansible_port: 8000
      ansible_user: databaseSSH
      ansible_become_password: databaseSSH
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa

    backend:
      ansible_host: 172.18.0.2
      ansible_port: 8001
      ansible_user: backendDeploySSH
      ansible_become_password: backendDeploySSH 
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa

