---
- name: Configure Tomcat for database connection
  ansible.builtin.template:
    src: "server.xml.j2"
    dest: "{{tomcat_install_dir}}/conf/server.xml"
  notify:
    - Restart Tomcat

- name: Ensure database is up and running
  ansible.builtin.command:
    cmd: "mysql -u {{ db_user }} -p{{ db_password }} -e 'SHOW DATABASES LIKE \"teachua\";'"
  register: db_check
  failed_when: db_check.rc != 0

- name: Restart Tomcat
  ansible.builtin.shell:
    cmd: "nohup {{ tomcat_install_dir }}/bin/catalina.sh restart > /opt/tomcat/logs/catalina.out 2>&1 &"
  become: yes
